questbook/grants-frontend

- src/components/explore_grants/apply_grant/form/index.tsx
- src/components/signup/create_dao/form.tsx
- src/components/signup/daoCreated.tsx
- src/components/ui/tooltip.tsx
Tooltip highlights the network the user is currently on, when signing up.
> Tooltip text made bold

- src/components/ui/forms/dropdown.tsx
fixes https://github.com/questbook/grants-frontend/issues/78
> currency dropdown fix

- src/components/your_applications/yourApplicationCard/checkPoint.tsx
> Fixed #120

- src/components/settings_and_members/settings.tsx
fixes https://github.com/questbook/grants-frontend/issues/135
> view profile preview fix

- package-lock.json
- package.json
- pages/connect_wallet.tsx
- pages/your_grants/edit_grant.tsx
- src/components/your_grants/edit_grant/form/4_rewards.tsx
- src/hooks/useAddMember.ts
- src/hooks/useApproveMilestone.ts
- src/hooks/useCompleteApplication.ts
- src/hooks/useCreateGrant.ts
- src/hooks/useCreateWorkspace.ts
- src/hooks/useDepositFunds.ts
- src/hooks/useDisburseP2PReward.ts
- src/hooks/useDisburseReward.ts
- src/hooks/useEditGrant.ts
- src/hooks/useRequestMilestoneApproval.ts
- src/hooks/useResubmitApplication.ts
- src/hooks/useSubmitApplication.ts
- src/hooks/useUpdateApplicationState.ts
- src/hooks/useUpdateWorkspace.ts
- src/hooks/useWithdrawFunds.ts
- src/utils/errorUtils.tsx
> 103 metamask connect error message

- src/components/ui/forms/singleLineInput.tsx
fixes https://github.com/questbook/grants-frontend/issues/130
> numeric input scroll fix

- src/components/settings_and_members/edit_form.tsx
- src/components/your_grants/manage_grant/modals/modalContentMilestoneDoneConfirmation.tsx
- src/components/your_grants/manage_grant/sidebar.tsx
- src/components/your_grants/view_applicants/states.tsx
- src/components/your_grants/view_applicants/table/TableFilters.tsx
> Copy issues fixed

- src/components/navbar/connected/index.tsx
fixes https://github.com/questbook/grants-frontend/issues/82
> workspace dropdown scrollbar fix

- pages/connect_wallet.tsx
> Removed tooltip

- graphql/getNumberOfGrants.graphql
- src/components/navbar/connected/index.tsx
- src/generated/graphql.ts
> Schema stitching for application and grant count

- src/components/signup/create_dao/form.tsx
> Limited maximum image upload size to 2 MB

- src/components/signup/create_dao/loading.tsx
> Removed timeElapsed when Signing up

- package-lock.json
- pages/connect_wallet.tsx
- pages/signup.tsx
- pages/your_grants/view_applicants/manage.tsx
- src/components/browse_grants/grantCard/index.tsx
- src/components/browse_grants/sidebar/index.tsx
- src/components/funds/add_funds_modal/index.tsx
- src/components/get_started/dao.tsx
- src/components/get_started/talent.tsx
- src/components/signup/daoCreated.tsx
- src/components/your_grants/add_funds_modal/index.tsx
- src/components/your_grants/manage_grant/modals/addFundModal.tsx
- src/components/your_grants/manage_grant/sidebar.tsx
- src/components/your_grants/sidebar/sidebar.tsx
- src/constants/strings.json
- src/hooks/useCreateWorkspace.ts
fixes https://github.com/questbook/grants-frontend/issues/89
> 89 broken links

- src/components/explore_grants/apply_grant/form/2_aboutTeam.tsx
- src/components/explore_grants/apply_grant/form/3_aboutProject.tsx
- src/components/ui/forms/select.tsx
- src/components/your_applications/grant_application/form/2_aboutTeam.tsx
- src/components/your_applications/grant_application/form/3_aboutProject.tsx
> Select menu added

- src/constants/chainInfo.ts
Reverts questbook/grants-frontend#162
> Revert "Removed Wallet Connect Support"

- pages/your_applications/index.tsx
Sorting applications in descending order based on their last updated
> My Applications sorting

- pages/your_grants/index.tsx
- src/components/signup/create_grant/form/3_applicantDetails.tsx
- src/components/ui/submitPublicKeyModal.tsx
- src/components/ui/toasts/successToast.tsx
- src/components/your_grants/create_grant/form/3_applicantDetails.tsx
- src/components/your_grants/create_grant/form/index.tsx
- src/components/your_grants/sidebar/sidebar.tsx
- src/hooks/useSubmitPublicKey.tsx
- added submit public key feat in invite member flow | 
- added notion links and tooltip labels
> feat: added submit public key feat in invite member flow | chore: notion link and tooltip

- src/constants/chainInfo.ts
Changed token addresses to lowercase in `chaininfo.ts`
> fix: changed token address to lowercase

- src/constants/chainInfo.ts
Fixed all addresses to lowercase in `chainInfo.ts`
> changed all token addresses to lowercase

- src/components/signup/create_grant/form/4_rewards.tsx
- src/components/ui/forms/dropdown.tsx
- src/components/ui/submitCustomTokenModal.tsx
- src/components/your_grants/create_grant/form/4_rewards.tsx
- src/components/your_grants/create_grant/form/index.tsx
- src/hooks/useCreateGrant.ts
- src/utils/formattingUtils.tsx
This PR fixes the issue - Grants not being created
This issue was due to posting an incorrect reward format while sending grant data during creation.
Note - **Reward format changes based on the type of token being used as a Reward.**
- If Reward uses default token, reward format:
`reward:  {
asset: string,
committed: string
}`
- If Reward uses a custom token, reward format:
`reward:  {
asset: string,
committed: string,
token: {
label: string,
address: string,
iconHash: string,
decimal: string
}
}`
_We need to ensure that the reward is in the correct format while sending the grant data._
> New erc token

- src/components/funds/index.tsx
- src/components/your_grants/yourGrantCard/index.tsx
This PR helps display token icons with uniform size
> chore: add size constraints to token icons

- pages/explore_grants/apply.tsx
- pages/your_applications/grant_application.tsx
- pages/your_applications/manage_grant.tsx
- src/components/explore_grants/apply_grant/form/index.tsx
- src/components/ui/submitCustomTokenModal.tsx
- src/components/your_applications/manage_grant/fundingRequestedTable.tsx
- src/components/your_grants/applicant_form/application.tsx
- src/components/your_grants/create_grant/form/4_rewards.tsx
- src/hooks/useCreateGrant.ts
- src/hooks/useSubmitApplication.ts
This PR contains fixes for custom token icons not appearing in the funding received table
> fix: fix custom tokens not visible

- src/components/signup/create_grant/form/4_rewards.tsx
This PR fixes the issue:
- Unable to create grants first time after signup
Reference doc: https://www.notion.so/questbook/Unable-to-create-a-grant-as-a-first-time-user-70c3b7931a6b432280d7358d7422e1e0
> fix: fix first time grant creation

- pages/explore_grants/about_grant.tsx
- src/components/explore_grants/about_grant/sidebar.tsx
Changes made in this pull request target the case when users view a grant they have already applied to.
> change sidebar text if user has already applied

- pages/explore_grants/about_grant.tsx
This PR solves the issue - [Grant details not showing up](https://www.notion.so/questbook/Grant-details-are-not-showing-up-09245cf5fcb54839b4e6cdfd3661549b)
> fix: fix grant details not showing up

- pages/signup.tsx
- public/ui_icons/back.svg
- src/components/signup/create_grant/form/1_title.tsx
- src/components/signup/create_grant/form/2_details.tsx
- src/components/signup/create_grant/form/3_applicantDetails.tsx
- src/components/signup/create_grant/form/4_rewards.tsx
- src/components/signup/create_grant/form/index.tsx
- src/components/signup/create_grant/index.tsx
This PR aims to add a back button to the first grant creation flow.
> Back button added

- src/components/navbar/connected/index.tsx
- src/layout/navbarLayout.tsx
This PR fixes the issue where in, when on the "Discover grants" page, no other DAO related tabs are displayed.
> Tab render issue fixed

- src/components/signup/create_dao/form.tsx
- src/components/ui/secondaryDropdown.tsx
This PR implements the feature - [Letting users switch network from the create DAO screen](https://www.notion.so/questbook/Letting-users-switch-network-from-the-create-DAO-screen-5361ba6d32bb47f8b0f8ae738cc8c93c)
> feat: let users switch network from the create DAO screen

- src/components/explore_grants/apply_grant/form/5_customFields.tsx
- src/components/signup/create_grant/form/3_applicantDetails.tsx
- src/components/your_applications/grant_application/form/5_customFields.tsx
- src/components/your_grants/applicant_form/application.tsx
- src/components/your_grants/create_grant/form/3_applicantDetails.tsx
- src/components/your_grants/edit_grant/form/3_applicantDetails.tsx
- src/constants/applicantDetailsList.tsx
1. Other information tab name changed to Add Custom Field
2. Custom Field question length increased to 300
> Copy changes

- src/components/your_grants/applicant_form/application.tsx
- src/theme/components/header.tsx
- src/theme/components/text.tsx
This PR implements the issue - [Milestone text should be given more emphasis than the Milestone heading ](https://www.notion.so/questbook/Milestone-text-should-be-given-more-emphasis-than-the-Milestone-heading-2177cb82f13245bcbe338559596a8112)
> chore: emphasize milestone text

- src/generated/graphql.ts
- src/hooks/utils/useChainId.ts
- src/utils/validationUtils.tsx
This PR adds support for Optimism-Kovan Network. With this we are live on Optimism-kovan
> feat: Add Optimism-Kovan network

- src/utils/formattingUtils.tsx
Reverts questbook/grants-frontend#396
> Revert "added right url"

- src/generated/graphql.ts
- src/hooks/useCreateWorkspace.ts
- src/hooks/utils/useChainId.ts
- src/utils/validationUtils.tsx
refactor code to use generated SupportedChainId.ts file as the source of truth for network details
> chore: automate adding new network

- pages/your_applications/grant_application.tsx
- pages/your_grants/view_applicants/applicant_form.tsx
- src/components/explore_grants/apply_grant/form/index.tsx
- src/components/your_applications/grant_application/form/index.tsx
- src/components/your_grants/applicant_form/application.tsx
- src/constants/applicantDetailsList.tsx
This PR makes the funding breakdown field an optional one while creating a grant and applying to it.
> Funding breakdown made optional

- pages/explore_grants/about_grant.tsx
- pages/explore_grants/apply.tsx
- pages/index.tsx
- pages/profile.tsx
- pages/your_applications/manage_grant.tsx
- pages/your_grants/index.tsx
- src/utils/tokenUtils.tsx
This PR fixes the issue of some icons not loading on the home screen and other parts of the product
> Currency Icons

- pages/index.tsx
This PR fixes [Unable to scroll till the bottom](https://www.notion.so/questbook/Unable-to-scroll-till-the-bottom-8cbc71bb242746fdb71c027b02ef0f18)
> fix: scroll to bottom

- src/components/your_grants/manage_grant/modals/ApproveFundModalContent.tsx
- src/components/your_grants/manage_grant/sidebar.tsx
- src/constants/config.json
- src/hooks/useDisburseP2PReward.ts
This PR updates the copy for fund approval and disbursal
> chore: update fund disbursal copies

- graphql/getNumberOfApplications.graphql
- pages/browse_dao.tsx
- src/components/navbar/connected/index.tsx
- src/generated/contracts/factories/index.ts
- src/generated/contracts/index.ts
- src/generated/graphql.ts
- src/v2/components/Sidebar/Tabs.tsx
This PR fixes the issue that `My Applications` being invisible upon connecting the wallet.
> fix: my applications not visible

- package-lock.json
- src/components/manage_dao/edit_form.tsx
- src/utils/settingsUtils.tsx
This PR unblocks DAO Admins to manage the data
> fix: Update Workspace Data

- pages/onboarding/create-domain.tsx
- src/components/browse_daos/get_started_card.tsx
- src/components/your_grants/edit_grant/form/3_applicantDetails.tsx
- src/hooks/useSafeUSDBalances.ts
- src/utils/formattingUtils.tsx
- src/v2/components/InputFields/TextField.tsx
- src/v2/components/Onboarding/CreateDomain/SafeDetails.tsx
This PR fixes some bugs that were hampering the UX of the product.
> Onboarding

- pages/onboarding/create-domain.tsx
- pages/v2/your_grants/view_applicants.tsx
- src/graphql/subgraph.tsx
- src/hooks/useBatchUpdateApplicationState.ts
- src/v2/payouts/InReviewProposals/InReviewPanel.tsx
- src/v2/payouts/SetupEvaluationDrawer/SetupEvaluationDrawer.tsx
This PR adds network modals (including a step that waits for transaction to index) to all the pages that are a part of the new design.
> chore: added network modals to new design pages

- pages/_app.tsx
- src/hooks/gasless/useBiconomy.ts
- src/utils/gaslessUtils.ts
Refactored biconomy initialization and scw deployment flow.
> Use biconomy refactor

- src/v2/payouts/SendFunds.tsx
Using already existing utils functions
> fix: the way milestone amount was parsed

- pages/browse_dao.tsx
- src/components/browse_daos/all_daos.tsx
- src/components/browse_daos/loadMoreCard.tsx
This PR adds a `Load More` button to the Browse Dao page.
> fix: Added Load More button to Browse Dao page

- src/v2/components/VerifySignerModal/index.tsx
Replace Discord link with Papercups
> replace discord with papercups

- src/v2/components/MigrateToGasless/index.tsx
We're adding a record for every workspace the user have in our database to track gas usage for all his domains.
Only support migrating DAOs on networks: Polygon, Celo, Optimism, and Goerli testnet.
> add: added workspace owners to database - gasless migration

- package-lock.json
- src/components/ui/forms/datepicker.tsx
- src/components/your_grants/create_grant/form/index.tsx
> bugfix: min date in html date input

- src/pages/_app.tsx
Added functions importWebwallet and exportWebwallet to WebwalletContext. 
Can be used anywhere in the code.
> add: import/export webwallet privateKey

- src/screens/proposal/index.tsx
- src/v2/payouts/SendFunds.tsx
- src/v2/payouts/SendFundsDrawer/DropdownSelect.tsx
- src/v2/payouts/SendFundsDrawer/RecepientDetails.tsx
- src/v2/payouts/SendFundsDrawer/SendFundsDrawer.tsx
- src/v2/payouts/SendFundsModal/RecepientDetails.tsx
- src/v2/payouts/SendFundsModal/SendFundsModal.tsx
This PR 
1. Adds commas to funding asked amount value
2. Shows default reward amount asked for a milestone in the Send Fund drawer and modal
_Note: These changes have been done after the feedback from Andrea (Solana)_
> Payout amount

- src/hooks/useSafeUSDBalances.ts
- src/v2/components/Safe/Dashboard.tsx
- src/v2/constants/safe/gnosis_safe.tsx
- src/v2/utils/gnosisUtils.tsx
This PR fixes Telos Safe integration issues that bumped up after package upgradation
> Fix Telos issues

- src/utils/gaslessUtils.ts
Removing charge_gas api call for the sake of a deadline
> fix: removed charge_gas api call

- next.config.js
- package-lock.json
- package.json
- src/components/explore_grants/apply_grant/form/1_applicantDetails.tsx
- src/components/explore_grants/apply_grant/form/index.tsx
- src/utils/appCopy.ts
- src/v2/payouts/SendFunds.tsx
Applicants can enter their unstoppable domain name instead of their wallet address to receive funds
> Integrate Unstoppable Domain 

- graphql/getReviewersForAWorkspace.graphql
- package-lock.json
- src/generated/graphql.ts
- src/screens/view_proposals/index.tsx
- src/types/index.ts
- src/v2/payouts/SetupEvaluationDrawer/AssignReviewers.tsx
- src/v2/payouts/SetupEvaluationDrawer/SetupEvaluationDrawer.tsx
This PR does the following changes:
1. Show only reviewers when auto assigning them to a grant
2. Preserve the privacy selection for reviews, that was set when creating the grant, in the reviewer selection sidebar
> fix: reviewers list when auto assigning fixed

- src/libraries/ui/FlushedInput.tsx
- src/libraries/ui/ImageUpload.tsx
- src/libraries/ui/NavBar/_components/AccountDetails.tsx
- src/libraries/ui/NavBar/_components/AddMemberButton.tsx
- src/screens/proposal_form/index.tsx
- src/screens/request_proposal/_components/VerifySignerModal.tsx
- src/screens/request_proposal/_subscreens/BuilderDiscovery.tsx
- src/screens/request_proposal/_subscreens/LinkMultiSig.tsx
- src/screens/request_proposal/_subscreens/Payouts.tsx
- src/screens/request_proposal/_subscreens/ProposalReview.tsx
- src/screens/request_proposal/_subscreens/ProposalSubmission.tsx
- src/theme/components/text.tsx
This fixes the following issues listed on Notion:
1. https://www.notion.so/questbook/Font-broken-in-Proposal-List-be41766299c24bcda12f493d2de992fb
2. https://www.notion.so/questbook/Image-broken-db75af6475ba47e2aa098345d2d84d2b
3. https://www.notion.so/questbook/Logo-is-not-used-6031cdc4a972444388d6a3b8d6a272f9
4. https://www.notion.so/questbook/Profile-dropdown-ugly-186dae91bae9462187d93c243ff887d4
5. https://www.notion.so/questbook/Error-saving-profile-372b23d86bbb4ec29b5ea1ea69677849
6. https://www.notion.so/questbook/Copy-CTA-not-visible-not-intuitive-128fa0c4a1cd482cb64cd2b14f12a4f0
> Phase 1 fix

- src/components/profile/grantCard/index.tsx
- src/screens/proposal_form/index.tsx
This PR fixes https://www.notion.so/questbook/Unreadable-CTA-927ae7bef1d34ab68d2a5c8f987ea634
> fix: submit proposal button not visible

- src/libraries/utils/pii.ts
- src/libraries/utils/types.ts
- src/screens/dashboard/_components/Body/SingleSelect/Discussions.tsx
- src/screens/dashboard/_hooks/useAddComment.ts
- src/screens/dashboard/_hooks/useGetComments.ts
- src/screens/dashboard/_hooks/useQuickReplies.ts
This PR adds various tags to the comments that would be added to proposals.
> chore: added tags in the discussion panel

- src/screens/dashboard/FundBuilderModal.tsx
- src/screens/proposal_form/index.tsx
Custom field viewing issue when submitting a proposal.
> fix: show custom fields

- src/generated/graphql.ts
- src/libraries/hooks/useFunctionCall.tsx
- src/libraries/ui/NavBar/_components/AccountDetails.tsx
- src/libraries/utils/pii.ts
- src/pages/_app.tsx
- src/screens/dashboard/SendAnUpdateModal.tsx
- src/screens/dashboard/_components/ActionList/SingleSelect/Reviews.tsx
- src/screens/dashboard/_components/Body/SingleSelect/Discussions.tsx
- src/screens/dashboard/_graphql/getComments.graphql
- src/screens/dashboard/_hooks/useAddComment.ts
- src/screens/dashboard/_hooks/useAddComments.ts
- src/screens/dashboard/_hooks/useAssignReviewers.ts
- src/screens/dashboard/_hooks/useGetComments.ts
- src/screens/dashboard/_hooks/useQuickReplies.ts
- src/screens/dashboard/_hooks/useSetRubrics.ts
This PR does the following:
1. Resolves issue around posting a comment
2. Updates the tags that can be added to proposals
3. Replaces TextEditor with a simpler TextArea for posting comments
4. Added loading states to buttons.
5. Shows the added profile picture in the account detail dropdown.
> Discussion

- src/screens/request_proposal/index.tsx
The grant page was now showing up when pressing "Okay" after creating a grant. Fixed.
> fix: grant now showing up after creation

- src/libraries/ui/NavBar/_components/BackupWallet.tsx
- src/libraries/ui/NavBar/_components/RestoreWallet.tsx
- src/libraries/ui/NavBar/_components/SignIn.tsx
- src/libraries/ui/NavBar/_components/googleRecovery.ts
Fix Google recovery popup closed issue. Change toast messages.
> Google-recovery-fix

- next.config.js
- package-lock.json
- src/contexts/safeContext.tsx
- src/libraries/ui/CustomSelect.tsx
- src/libraries/ui/LinkYourMultisigModal/DropdownSelect.tsx
- src/libraries/ui/LinkYourMultisigModal/SafeSelect.tsx
- src/libraries/ui/LinkYourMultisigModal/index.tsx
- src/libraries/ui/NavBar/_components/BackupWallet.tsx
- src/libraries/ui/NavBar/_components/CreateNewWallet.tsx
- src/libraries/ui/NavBar/_components/RestoreWallet.tsx
- src/pages/_app.tsx
- src/screens/dashboard/Context.tsx
- src/screens/dashboard/FundBuilderDrawer.tsx
- src/screens/dashboard/FundBuilderModal.tsx
- src/screens/dashboard/_components/ActionList/MultiSelect/index.tsx
- src/screens/dashboard/_components/FundBuilder/MilestoneChoose.tsx
- src/screens/dashboard/_components/FundBuilder/PayFromChoose.tsx
- src/screens/dashboard/_components/FundBuilder/PayWithChoose.tsx
- src/screens/dashboard/_components/FundBuilder/ProposalDetails.tsx
- src/screens/dashboard/_components/FundBuilder/TransactionInitiated.tsx
- src/screens/dashboard/_components/FundBuilder/Verify.tsx
- src/screens/dashboard/_utils/types.ts
- src/screens/proposal_form/Context.tsx
- src/screens/proposal_form/index.tsx
- src/types/gasless.ts
- src/types/index.ts
This PR does the following:
1. Resolve all linter issues
2. Enables eslint check when running `npm run build`
> chore: resolve lint issues

- package-lock.json
- package.json
- src/libraries/ui/NavBar/_components/OptimismWarning.tsx
- src/libraries/ui/NavBar/index.tsx
A banner to warn the users about the upcoming optimism upgrade soon
https://oplabs.notion.site/Bedrock-Mission-Control-EXTERNAL-fca344b1f799447cb1bcf3aae62157c5
> Optimism upgrade warning

- src/screens/dashboard/ProposalList.tsx
- src/screens/dashboard/_components/ActionList/SingleSelect/index.tsx
Reverts questbook/grants-frontend#776
> Revert "fixing bugs"

- package-lock.json
- src/constants/safesSupported.json
- src/pages/_app.tsx
Reverts questbook/grants-frontend#790
> Revert "add: the rest of supported safes networks to wagmi"

- next.config.js
- package-lock.json
- package.json
- src/libraries/hooks/useQBContract.ts
- src/libraries/hooks/useUpdateDaoVisibility.ts
- src/libraries/ui/LinkYourMultisigModal/VerifySignerModal.tsx
- src/libraries/utils/invite.ts
- src/pages/_app.tsx
- src/screens/settings/index.tsx
- src/screens/setup_profile/index.tsx
Reverts questbook/grants-frontend#788
> Revert "Upgrade wagmi version"

- src/screens/dashboard/Context.tsx
A PR to sort the proposals by last interaction of an admin or a reviewer. Moreover, if the user has submitted any proposals, they will appear at the top.
> Sort proposals

- next.config.js
- package-lock.json
- package.json
- src/libraries/hooks/useQBContract.ts
- src/libraries/hooks/useUpdateDaoVisibility.ts
- src/libraries/ui/LinkYourMultisigModal/VerifySignerModal.tsx
- src/libraries/utils/invite.ts
- src/pages/_app.tsx
- src/screens/dashboard/_components/FundBuilder/Verify.tsx
- src/screens/setup_profile/index.tsx
Reverts questbook/grants-frontend#808
> Revert "Wallet connect fix"

- package-lock.json
- package.json
- src/screens/dashboard/FundBuilderModal.tsx
- src/screens/dashboard/_components/FundBuilder/PayWithChoose.tsx
- src/screens/dashboard/_components/FundBuilder/ProposalDetails.tsx
removed parseFloat and string conversion
ref: https://github.com/questbook/supported-safes/pull/9
> fix: token conversion
